name: Apply Terraform

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/apply_terraform.yaml"
      - "cloudflare/**"

env:
  TF_VAR_cloudflare_api_token: ${{ secrets.CF_API_TOKEN }}
  TF_VAR_cloudflare_account_id: ${{ secrets.CF_ACCOUNT_ID }}

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.9.0
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Init
        working-directory: ./cloudflare
        run: terraform init

      - name: Terraform Plan
        working-directory: ./cloudflare
        run: terraform plan

      - name: Terraform Apply
        working-directory: ./cloudflare
        run: terraform apply -auto-approve
