name: Apply Terraform

on:
  push:
    branches:
      - main

env:
  CLOUDFLARE_EMAIL: ${{ secrets.CLOUDFLARE_EMAIL }}
  CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.9.0

      - name: Terraform Init
        working-directory: ./cloudflare
        run: terraform init

      - name: Terraform Plan
        working-directory: ./cloudflare
        run: terraform plan

      - name: Terraform Apply
        working-directory: ./cloudflare
        run: terraform apply -auto-approve
